#
# Base
#
FROM php:8.1-fpm-alpine

LABEL maintainer="Carlos Brighton cbrghton@brghton.dev"

COPY xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini
COPY supervisord-app.conf /etc/supervisord.conf

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# TODO: Maybe need purified 😬
# I preferred to get the node and npm package instead of using the image since all the libraries were joined
RUN apk --update --no-cache add \
    nodejs \
	npm \
    wget \
    curl \
    grep \
    neovim \
    bat \
    build-base \
    libmemcached-dev \
    libmcrypt-dev \
	libxml2-dev \
	imagemagick-dev \
	pcre-dev \
	libtool \
	make \
	autoconf \
	g++ \
	cyrus-sasl-dev \
	libgsasl-dev \
	libzip-dev \
    icu-data-full \
    oniguruma \
    oniguruma-dev \
	supervisor && \
    docker-php-ext-install \
	mysqli \
	mbstring \
	pdo \
	pdo_mysql \
	xml \
	bcmath \
	soap \
	zip && \
    pecl channel-update pecl.php.net && \
    pecl install memcached && \
    pecl install xdebug && \
    pecl install imagick && \
    pecl install mcrypt && \
    docker-php-ext-enable \
    memcached \
	imagick \
	mcrypt \
	xdebug && \
    composer global require squizlabs/php_codesniffer && \
    ln -s ~/.composer/vendor/bin/phpcs /usr/bin/phpcs && \
    rm -rf /var/cache/apk/* /tmp/* && \
    mkdir -p /var/www


#
# Version
#
ADD VERSION .


ENTRYPOINT ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisord.conf"]
