#
# Base
#
FROM php:5.6-fpm-alpine

LABEL maintainer="Carlos Brighton cbrghton@brghton.dev"

COPY xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini
COPY supervisord-app.conf /etc/supervisord.conf

COPY --from=composer /usr/bin/composer /usr/bin/composer

# TODO: Maybe need purified 😬
# I preferred to get the node and npm package instead of using the image since all the libraries were joined
RUN apk --update --no-cache add \
    nodejs \
    npm \
    wget \
    curl \
    grep \
    build-base \
    libmemcached-dev \
    libmcrypt-dev \
    libxml2-dev \
    imagemagick-dev \
    pcre-dev \
    libtool \
    make \
    autoconf \
    g++ \
    cyrus-sasl-dev \
    libgsasl-dev \
    libzip-dev \
    supervisor

RUN docker-php-ext-install \
    mysqli \
    mbstring \
    pdo \
    pdo_mysql \
    tokenizer \
    xml \
    bcmath \
    soap \
    zip

RUN pecl channel-update pecl.php.net && \
    pecl install memcached \
        xdebug \
        imagick \
        mcrypt-1.0.2

RUN docker-php-ext-enable \
    imagick \
    bcmath \
    mbstring \
    mysqli \
    pdo \
    pdo_mysql \
    soap \
    tokenizer \
    xml \
    zip

RUN composer global require squizlabs/php_codesniffer && \
    ln -s ~/.composer/vendor/bin/phpcs /usr/bin/phpcs && \
    rm -rf /var/cache/apk/* /tmp/* && \
    mkdir -p /var/www


#
# Version
#
ADD VERSION .


ENTRYPOINT ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisord.conf"]
